# -*- coding: utf-8 -*-
# Globals Config

# OSS API
OSS_HOST            =  'oss-cn-beijing.aliyuncs.com'
ACCESS_KEY_ID       =  'AiEAsvpEfF0N7X7p'
ACCESS_KEY_SECRET   =  '4MhEmNseXK5QvCrHRDSarJeNWKY9la'
OSS_BUCKET          =  'upload-items'
OSS_CONTENT_TYPE    =  'image/jpeg'
OSS_CDN_HOST        =  'http://upload-items.oss-cn-beijing.aliyuncs.com/'

TYPEDIC = {}
TYPEDIC['100'] = "书籍/英语"
TYPEDIC['101'] = "书籍/数物"
TYPEDIC['102'] = "书籍/电子-计算机"
TYPEDIC['103'] = "书籍/人文社科"
TYPEDIC['104'] = "书籍/经济"
TYPEDIC['105'] = "书籍/艺术"
TYPEDIC['106'] = "书籍/其他"
TYPEDIC['200'] = "化妆品/面膜"
TYPEDIC['201'] = "化妆品/水"
TYPEDIC['202'] = "化妆品/乳"
TYPEDIC['203'] = "化妆品/其他"
TYPEDIC['300'] = "数码/面膜"
TYPEDIC['301'] = "数码/电脑"
TYPEDIC['302'] = "数码/相机"
TYPEDIC['303'] = "数码/显示器"
TYPEDIC['400'] = "车/山地车"
TYPEDIC['401'] = "车/电动车"
TYPEDIC['402'] = "车/普通单车"
TYPEDIC['403'] = "车/死飞"
TYPEDIC['404'] = "车/其他" 
TYPEDIC['500'] = "运动/网球"
TYPEDIC['501'] = "运动/羽毛球"
TYPEDIC['502'] = "运动/足球"
TYPEDIC['503'] = "运动/篮球"
TYPEDIC['504'] = "运动/其他"
TYPEDIC['600'] = "服装/衣服"
TYPEDIC['601'] = "服装/外套"
TYPEDIC['602'] = "服装/其他"
TYPEDIC['700'] = "生活用品/沐浴露"
TYPEDIC['701'] = "生活用品/洗发水"
TYPEDIC['702'] = "生活用品/其他"
TYPEDIC['800'] = "手工艺品/首饰"
TYPEDIC['801'] = "手工艺品/其他"
TYPEDIC['900'] = "箱包"
TYPEDIC['901'] = "其他"